name: Run application via Docker Compose

on:
  workflow_call:
    inputs:
      enabled:
        type: boolean
        required: false
        default: true
      registry:
        type: string
        required: false
        default: 'ghcr.io'
      latest:
        type: string
        required: false
        default: 'false'
      prefix:
        type: string
        required: false
        default: ''
      suffix:
        type: string
        required: false
        default: ''
      compose_service:
        description: 'Docker compose service name for scaling'
        type: string
        required: true
        default: 'app'
      compose_path:
        description: 'Path ot Docker compose file'
        type: string
        required: false
        default: 'docker-compose.yml'
      compose_env_file_path:
        description: 'Path ot env_file file'
        type: string
        required: false
        default: ''
      docker_host:
        description: 'Docker host to run on'
        type: string
        required: true
      project:
        description: 'Compose project name'
        type: string
        required: true
      compose_timeout:
        description: 'Timeout in seconds for container shutdown when containers are already running'
        type: number
        required: false
        default: 10

jobs:
  compose-up:
    if: ${{ inputs.enabled }}
    runs-on: ci-server
    env:
      ENV_FILE_CONTENT_BASE64: ${{ secrets.ENV_FILE_CONTENT_BASE64 }}
      DOCKER_HOST: ${{ inputs.docker_host }}
      APP_ENV_FILE: ${{ inputs.compose_env_file_path }}
    steps:
      -
        name: cleanup
        run: sudo rm -fr $GITHUB_WORKSPACE && mkdir $GITHUB_WORKSPACE
      -
        name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.ref }}
      -
        name: Get Docker metadata
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ inputs.registry }}/${{ github.repository }}
          flavor: |
            latest=${{ inputs.latest }}
            prefix=${{ inputs.prefix }}
            suffix=${{ inputs.suffix }}
      -
        name: Login to Container Registry
        uses: docker/login-action@v2
        with:
          registry: ${{ inputs.registry }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Generate .env file from secrets
        if: ${{ env.ENV_FILE_CONTENT_BASE64 != '' }}
        run: >
          echo $ENV_FILE_CONTENT_BASE64 | base64 -d > ${{ inputs.compose_env_file_path }}
      -
        name: Lint and show compose manifest
        env:
          IMAGE_NAME: ${{ steps.meta.outputs.tags }}
        run: >
          /usr/bin/docker compose
          -p ${{ inputs.project }}
          -f ${{ inputs.compose_path }}
          --env-file ${{ inputs.compose_env_file_path }}
          convert ${{ inputs.compose_service }}
      -
        name: Pre-pull new Docker-image
        env:
          IMAGE_NAME: ${{ steps.meta.outputs.tags }}
        run: >
          /usr/bin/docker compose
          -p ${{ inputs.project }}
          -f ${{ inputs.compose_path }}
          --env-file ${{ inputs.compose_env_file_path }}
          pull --quiet ${{ inputs.compose_service }}
      -
        name: Update and start App
        env:
          IMAGE_NAME: ${{ steps.meta.outputs.tags }}
        run: >
          /usr/bin/docker compose
          -p ${{ inputs.project }}
          -f ${{ inputs.compose_path }}
          --env-file ${{ inputs.compose_env_file_path }}
          up --detach --timeout ${{ inputs.compose_timeout }} ${{ inputs.compose_service }}
